---
apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    certificate-authority-data: <CERTIFICATE AUTHORITY DATA>
    server: <SERVER>
users:
- name: <USERNAME>
  user:
    token: <TOKEN>
contexts:
- name: default
  context:
    cluster: default
    user: <USERNAME>
    namespace: default
current-context: default
