model_configs_path: '<PATH TO AISK REPO HERE>/benchmarking/benchmarking_scripts/model_configs_example.csv'
llm_api: 'sncloud'
output_files_dir: '<PATH TO AISK REPO HERE>/benchmarking/data/benchmarking_tracking_tests/logs/output_files'
consolidated_results_dir: '<PATH TO AISK REPO HERE>/benchmarking/data/benchmarking_tracking_tests/consolidated_results'
timeout: 3600
time_delay: 0
# Row-level concurrency
concurrency_enabled: False
max_workers: 4 # Only used if concurrency_enabled is True
# Prompt behavior
use_multiple_prompts : False # Only available for synthetic performance evaluation