model_configs_path: '../benchmarking/benchmarking_scripts/model_configs_example.csv'
llm_api: 'sncloud'
output_files_dir: '../benchmarking/data/adhoc_tests/reggie_ricoh_tests/'
consolidated_results_dir: '../benchmarking/data/adhoc_tests/reggie_ricoh_tests//consolidated_results'
timeout: 3600
time_delay: 0
use_multiple_prompts : False # Only available for synthetic performance evaluation