api: "sambastudio"

embedding_model: "cpu"

loaders: 
    pdf: "unstructured"
    txt: "text_loader"

llm: 
    "temperature": 0.0
    "max_tokens_to_generate": 1200
    "sambaverse_model_name": "Meta/llama-2-70b-chat-hf"
    "sambaverse_select_expert": "llama-2-70b-chat-hf"

retrieval:
    "chunk_size": 1200
    "chunk_overlap": 240
    "db_type": "chroma"
    "k_retrieved_documents": 3
    "score_threshold": 0.6

