api: "sambastudio"

embedding_model: "sambastudio"

loaders: 
    pdf: "unstructured"
    txt: "text_loader"

llm: 
    "temperature": 0.0
    "max_tokens_to_generate": 3000
    "sambaverse_model_name": "Meta/llama-3-70b-chat-hf"
    "sambaverse_select_expert": "Meta-Llama-3-70B-Instruct"

retrieval:
    "chunk_size": 1024
    "chunk_overlap": 240
    "example_selector_k": 1
    "entity_key": "filename"
    "k_retrieved_documents": 20
    "score_threshold": 0.2
    "rerank": True
    "reranker": 'BAAI/bge-reranker-large'
    "final_k_retrieved_documents": 3

prompts: 
    "router_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-subquery_router.yaml"
    "example_judge_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-example_judge.yaml"
    "reformulation_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-query_reformulation.yaml"
    "entity_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-entity_determination.yaml"
    "subquery_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-subquery_generation.yaml"
    "retrieval_grader_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-retrieval_grading.yaml"
    "qa_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-qa.yaml"
    "hallucination_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-hallucination_detection.yaml"
    "grading_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-answer_grading.yaml"
    "code_router_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-code_router.yaml"
    "codegen_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-codegen.yaml"
    "codegen_qc_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-codegen_qc.yaml"
    "refactor_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-code_refactor.yaml"
    "failure_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-code_exec_failure.yaml"
    "aggregation_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-answer_aggregation.yaml"
    "final_chain_prompt": "prompt_engineering/prompts/llama3_8b-prompt_engineering-final_chain.yaml"