audio_model:
    "type": "sncloud" #  set either sambastudio or sncloud
    "temperature": 0.0
    "model": "Qwen2-Audio-7B-Instruct"
    "max_tokens": 1200

llm: 
    "type": "sncloud" #  set either sambastudio or sncloud
    "temperature": 0.01
    "do_sample": False
    "max_tokens": 1200
    "model": "Meta-Llama-3.3-70B-Instruct" #set if using sncloud, SambaStudio bundle llm expert

prod_mode: False
