sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"

project:
  project_name: "byoc-fine-tuning-project"
  project_description: "this project will be used to test the BYOC and Fine-tuning e2e pipeline implementation"

composite_model:
  model_name:  "Suzume-Llama-3-8B-Multilingual-Bundle"
  description: "Bundle including base and public health fine-tuned Suzume-Llama-3-8B-Multilingual"
  rdu_required: 8
  model_version: '1'
  model_list:
    - "Suzume-Llama-3-8B-Multilingual"
    - "Suzume-Llama-3-8B-Multilingual-Publichealth"

endpoint:
  endpoint_name: "suzume-multilingual-endpoint"
  endpoint_description: "endpoint for suzume multilingual bundle"
  endpoint_instances: 1
  hyperparams: null